package main

import (
	"fmt"

	"github.com/sait/go-conekta/conekta"
)

func main() {
	fmt.Println("Hello conekta")
	conekta.ApiKey = "<My Secret ApiKey>"
	fmt.Println("Creating an order")
	order := new(conekta.Order)
	fmt.Println("Creating an item")
	item := conekta.LineItem{
		Name:        "Awesome item",
		Description: "Super Awesome item",
		UnitPrice:   20000,
		Quantity:    2,
	}
	order.LineItems = append(order.LineItems, item)
	fmt.Println("Setting currency")
	order.Currency = "MXN"
	fmt.Println("Creating charge")
	charge := conekta.Charge{
		PaymentMethod: conekta.PaymentMethod{
			Type:    "card",
			TokenId: "<token generated by frontend>",
		},
	}
	order.Charges = append(order.Charges, charge)
	fmt.Println("Adding some metadata")
	order.Metadata = conekta.Metadata{
		"test": "extra_info",
		"hola": "mundo",
	}
	fmt.Println("Setting customer info")
	order.CustomerInfo.Name = "Fulanito Pérez"
	order.CustomerInfo.Email = "fulanito@conekta.com"
	order.CustomerInfo.Phone = "+52181818181"
	fmt.Println("Sending order to conekta")
	statusCode, conektaError := order.Create()
	if conektaError != nil {
		panic(conektaError)
	}
	if statusCode != 200 {
		fmt.Println("There's a problem :(")
		return
	}
	fmt.Println("Congratulations!!")
}
